#!/usr/bin/dotnet run
// Generates CLI help documentation for the Shelly CLI by invoking `shelly cli xmldoc`.

#:sdk Microsoft.NET.Sdk
#:property TargetFramework=net10.0
#:property Nullable=enable
#:property ImplicitUsings=enable

using System.Diagnostics;
using System.Text;
using System.Xml.Linq;

const string shellyBin = "shelly";
var cwd = Directory.GetCurrentDirectory();
var outputFile = Path.Combine(cwd, "wiki", "cli_help.md");

var xml = RunXmlDoc();
var doc = XDocument.Parse(xml);

// List of <Command> elements directly under <Model>
var commands = doc.Root?.Elements("Command").ToList()
               ?? throw new InvalidOperationException("Unexpected xmldoc structure: missing <Model> root.");

Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);

var sb = new StringBuilder();
sb.AppendLine("# Shelly CLI Documentation");
sb.AppendLine();
sb.AppendLine("> Auto-generated by `help_compiler.cs`. Do not edit manually.");

WriteSummary(sb, commands);

sb.AppendLine();
sb.AppendLine("---");
sb.AppendLine();
sb.AppendLine("## Command Reference");

foreach (var cmd in commands)
    WriteCommand(sb, cmd, "shelly");

File.WriteAllText(outputFile, sb.ToString());
Console.WriteLine($"Documented {doc.Descendants("Command").Count()} commands.");
Console.WriteLine($"Documentation written to {outputFile}");
return;

#region Helpers

static string RunXmlDoc()
{
    try
    {
        var psi = new ProcessStartInfo(shellyBin, ["cli", "xmldoc"])
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };

        using var proc = Process.Start(psi)!;
        var stdout = proc.StandardOutput.ReadToEnd();
        proc.WaitForExit();

        return string.IsNullOrWhiteSpace(stdout)
            ? throw new InvalidOperationException("No output from 'shelly cli xmldoc'.")
            : stdout;
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"ERROR: Could not run '{shellyBin} cli xmldoc': {ex.Message}");
        Console.Error.WriteLine("Build and install the project first (dotnet publish Shelly-CLI).");
        Environment.Exit(1);
        return "";
    }
}

static void WriteSummary(StringBuilder sb, List<XElement> commands)
{
    sb.AppendLine();
    sb.AppendLine("## Overview");
    sb.AppendLine();

    var rootCmds = commands
        .Where(c => c.Attribute("IsBranch")?.Value != "true" && c.Attribute("IsDefault")?.Value != "true")
        .ToList();

    if (rootCmds.Count > 0)
    {
        sb.AppendLine("### Package Management");
        sb.AppendLine();
        WriteCommandTable(sb, rootCmds, "");
    }

    foreach (var branch in commands.Where(c => c.Attribute("IsBranch")?.Value == "true"))
    {
        var branchName = branch.Attribute("Name")?.Value ?? "";
        var branchDesc = branch.Element("Description")?.Value.Trim() ?? "";

        var heading = string.IsNullOrWhiteSpace(branchDesc)
            ? $"`{branchName}`"
            : $"{branchDesc} (`{branchName}`)";

        sb.AppendLine($"### {heading}");
        sb.AppendLine();
        WriteCommandTable(sb, branch.Elements("Command").ToList(), branchName);
    }
}

static void WriteCommandTable(StringBuilder sb, List<XElement> cmds, string prefix)
{
    if (cmds.Count == 0) return;

    var rows = cmds.Select(cmd =>
    {
        var name = cmd.Attribute("Name")?.Value ?? "";
        var desc = cmd.Element("Description")?.Value.Trim() ?? "";
        var args = cmd.Element("Parameters")?.Elements("Argument").ToList() ?? [];

        var sig = string.IsNullOrEmpty(prefix) ? name : $"{prefix} {name}";
        foreach (var arg in args)
        {
            var argName = arg.Attribute("Name")?.Value ?? "arg";
            var required = arg.Attribute("Required")?.Value == "true";
            sig += required ? $" <{argName}>" : $" [{argName}]";
        }

        return (Cell: $"`{sig}`", Desc: desc);
    }).ToList();

    var cmdWidth = Math.Max("Command".Length, rows.Max(r => r.Cell.Length));
    var descWidth = Math.Max("Description".Length, rows.Max(r => r.Desc.Length));

    sb.AppendLine($"| {"Command".PadRight(cmdWidth)} | {"Description".PadRight(descWidth)} |");
    sb.AppendLine($"|{new string('-', cmdWidth + 2)}|{new string('-', descWidth + 2)}|");
    foreach (var (cell, desc) in rows)
        sb.AppendLine($"| {cell.PadRight(cmdWidth)} | {desc.PadRight(descWidth)} |");
    sb.AppendLine();
}

static void WriteCommand(StringBuilder sb, XElement cmd, string parentDisplay)
{
    var name = cmd.Attribute("Name")?.Value ?? "";
    var isBranch = cmd.Attribute("IsBranch")?.Value == "true";
    var isDefault = cmd.Attribute("IsDefault")?.Value == "true";

    var displayPath = isDefault ? "shelly" : $"{parentDisplay} {name}";

    // Root token = first segment after "shelly" - used for example grouping
    var parts = displayPath.Split(' ');
    var rootToken = parts.Length > 1 ? parts[1] : name;

    var description = cmd.Element("Description")?.Value.Trim() ?? "";
    var arguments = cmd.Element("Parameters")?.Elements("Argument").ToList() ?? [];
    var options = cmd.Element("Parameters")?.Elements("Option").ToList() ?? [];
    var subCommands = cmd.Elements("Command").ToList();
    var examples = GroupExamples(cmd.Element("Examples")?.Elements("Example").ToList() ?? [], rootToken);

    sb.AppendLine();
    sb.AppendLine($"### `{displayPath}`");
    sb.AppendLine();

    if (!string.IsNullOrWhiteSpace(description))
    {
        sb.AppendLine(description);
        sb.AppendLine();
    }

    if (isBranch && subCommands.Count > 0)
    {
        sb.AppendLine("*Branch command — use one of the subcommands below.*");
        sb.AppendLine();
        sb.AppendLine("**Subcommands:**");
        sb.AppendLine();
        foreach (var sub in subCommands)
        {
            var subName = sub.Attribute("Name")?.Value ?? "";
            var subDesc = sub.Element("Description")?.Value.Trim() ?? "";
            sb.AppendLine($"- `{displayPath} {subName}` — {subDesc}");
        }

        sb.AppendLine();
    }

    if (arguments.Count > 0)
    {
        sb.AppendLine("**Arguments:**");
        sb.AppendLine();
        foreach (var arg in arguments)
        {
            var argName = arg.Attribute("Name")?.Value ?? "ARG";
            var required = arg.Attribute("Required")?.Value == "true";
            var argDesc = arg.Element("Description")?.Value.Trim() ?? "";
            var reqMarker = required ? " *(required)*" : "";
            sb.AppendLine($"- `<{argName}>`{reqMarker} — {argDesc}");
        }

        sb.AppendLine();
    }

    if (options.Count > 0)
    {
        sb.AppendLine("**Options:**");
        sb.AppendLine();
        foreach (var opt in options)
        {
            var shortOpt = opt.Attribute("Short")?.Value ?? "";
            var longOpt = opt.Attribute("Long")?.Value ?? "";
            var required = opt.Attribute("Required")?.Value == "true";
            var optDesc = opt.Element("Description")?.Value.Trim() ?? "";
            var reqMarker = required ? " *(required)*" : "";

            var flags = new[]
            {
                string.IsNullOrEmpty(shortOpt) ? null : $"-{shortOpt}",
                string.IsNullOrEmpty(longOpt) ? null : $"--{longOpt}"
            }.Where(f => f != null);

            sb.AppendLine($"- `{string.Join(", ", flags)}`{reqMarker} — {optDesc}");
        }

        sb.AppendLine();
    }

    if (examples.Count > 0)
    {
        sb.AppendLine("**Examples:**");
        sb.AppendLine();
        sb.AppendLine("```sh");
        foreach (var ex in examples)
            sb.AppendLine($"shelly {ex}");
        sb.AppendLine("```");
    }

    foreach (var sub in subCommands)
        WriteCommand(sb, sub, displayPath);
}

// Each argument in WithExample("a", "b", "c") becomes a separate <Example commandLine="..." />.
// We regroup them into full example lines by splitting on occurrences of the command name root token.
static List<string> GroupExamples(List<XElement> elements, string rootToken)
{
    var tokens = elements.Select(e => e.Attribute("commandLine")?.Value ?? "").ToList();
    if (tokens.Count == 0) return [];

    var result = new List<string>();
    var current = new List<string>();

    foreach (var token in tokens)
    {
        // A new example starts when we see the command name again (and we already have tokens)
        if (token == rootToken && current.Count > 0)
        {
            result.Add(string.Join(" ", current));
            current.Clear();
        }

        current.Add(token);
    }

    if (current.Count > 0)
        result.Add(string.Join(" ", current));

    return result;
}

#endregion
